name: finddy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  badges: ^3.1.1
  bloc: ^8.1.2
  camera: ^0.10.3+2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.8.2
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.2.0+1
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_feather_icons: ^2.0.0+1
  flutter_launcher_icons: ^0.11.0
  get_it: ^7.6.0
  go_router: ^7.1.1
  injectable: ^2.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  retrofit: ^4.0.1
  step_progress_indicator: ^1.0.2
  
  

dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0
  mockito: ^5.4.1
  retrofit_generator: ^7.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/img_findy_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: PlusJakartaDisplay
      fonts:
        - asset: assets/fonts/PlusJakartaDisplay-Bold.otf
        - asset: assets/fonts/PlusJakartaDisplay-BoldItalic.otf
        - asset: assets/fonts/PlusJakartaDisplay-Italic.otf
        - asset: assets/fonts/PlusJakartaDisplay-Light.otf
        - asset: assets/fonts/PlusJakartaDisplay-LightItalic.otf
        - asset: assets/fonts/PlusJakartaDisplay-Medium.otf
        - asset: assets/fonts/PlusJakartaDisplay-MediumItalic.otf
        - asset: assets/fonts/PlusJakartaDisplay-Regular.otf
    - family: PlusJakartaText
      fonts:
        - asset: assets/fonts/PlusJakartaText-BoldItalic.otf
        - asset: assets/fonts/PlusJakartaText-Italic.otf
        - asset: assets/fonts/PlusJakartaText-Light.otf
        - asset: assets/fonts/PlusJakartaText-LightItalic.otf
        - asset: assets/fonts/PlusJakartaText-Regular.otf
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
